
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab8(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N
);

SDRAM_PD U1(
		    .clk_clk(CLOCK_50),                     //                     clk.clk
			.pio_0_ec_export(LEDR),             //                pio_0_ec.export
			. pll_0_locked_export(),         //            pll_0_locked.export
			.pll_outclk1_phase_shift_clk(DRAM_CLK), // pll_outclk1_phase_shift.clk
			.reset_reset_n(KEY[0]),               //                   reset.reset_n
		 	.sdram_wire_addr(DRAM_ADDR),             //              sdram_wire.addr
		  	.sdram_wire_ba(DRAM_BA),               //                        .ba
		    .sdram_wire_cas_n(DRAM_CAS_N),            //                        .cas_n
		    .sdram_wire_cke(DRAM_CKE),              //                        .cke
		    .sdram_wire_cs_n(DRAM_CS_N),             //                        .cs_n
		  	.sdram_wire_dq(DRAM_DQ),               //                        .dq
		  	.sdram_wire_dqm({DRAM_UDQM,DRAM_LDQM}),              //                        .dqm
		    .sdram_wire_ras_n(DRAM_RAS_N),            //                        .ras_n
		 	.sdram_wire_we_n(DRAM_WE_N)              //                        .we_n
	);

//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
